# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HermesRemote < Formula
  desc "Pair the Hermes iPhone app with the Mac that runs Hermes"
  homepage "https://github.com/ShravanthReddy/hermes-remote"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/ShravanthReddy/hermes-remote/releases/download/v0.1.0/hermes-remote_0.1.0_darwin_universal.tar.gz"
    sha256 "8df7362ae14cb8465ae42e4486be3030e8c6888b700351a203d5098743362063"

    define_method(:install) do
      bin.install "hermes-remote"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ShravanthReddy/hermes-remote/releases/download/v0.1.0/hermes-remote_0.1.0_linux_amd64.tar.gz"
      sha256 "4f2c3b283e902bd5a7c5f923f5f02fad43d58a47307604a5ea7be100931d20bb"
      define_method(:install) do
        bin.install "hermes-remote"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ShravanthReddy/hermes-remote/releases/download/v0.1.0/hermes-remote_0.1.0_linux_arm64.tar.gz"
      sha256 "88ef123a8daa5376f90641044b65a2c995bed22da260cd34d24041dc9ade5177"
      define_method(:install) do
        bin.install "hermes-remote"
      end
    end
  end

  def caveats
    <<~EOS
      Start the bridge and show the pairing QR code:
        hermes-remote up
    EOS
  end

  test do
    system "#{bin}/hermes-remote", "version"
  end
end
