# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HermesRemote < Formula
  desc "Pair the Hermes iPhone app with the Mac that runs Hermes"
  homepage "https://github.com/ShravanthReddy/hermes-remote"
  version "0.12.0"
  license "MIT"

  on_macos do
    url "https://github.com/ShravanthReddy/hermes-remote/releases/download/v0.12.0/hermes-remote_0.12.0_darwin_universal.tar.gz"
    sha256 "a62ac041fc19fab5d0ab85027711c8a71efcbf6fa16ea79e6dc1208cb1688972"

    define_method(:install) do
      bin.install "hermes-remote"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ShravanthReddy/hermes-remote/releases/download/v0.12.0/hermes-remote_0.12.0_linux_amd64.tar.gz"
      sha256 "434975a6a46426c1da6d17f257a0de0bb77b16179cae28c46943b788afc70bc6"
      define_method(:install) do
        bin.install "hermes-remote"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ShravanthReddy/hermes-remote/releases/download/v0.12.0/hermes-remote_0.12.0_linux_arm64.tar.gz"
      sha256 "5a998f35a71f86645611a3ca90b8ef26a026d431433a5015461926dbbf441e57"
      define_method(:install) do
        bin.install "hermes-remote"
      end
    end
  end

  def caveats
    <<~EOS
      Start the bridge and show the pairing QR code:
        hermes-remote up
    EOS
  end

  test do
    system "#{bin}/hermes-remote", "version"
  end
end
